export const POSTS = [
  {    
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with ReactJS 😍",
    img: "/posts/post1.png",
    user: {
      userName: "vamsikrishnad",
      profileImg: "/avatars/boy1.png",
      fullName: "Vamsi Krishna D",
    },                                 
    comments: [
      {
        _id: "1",                
        text: "Nice Tutorial",      
        user: {
          userName: "vamsikrishnad",
          profileImg: "/avatars/girl1.png",
          fullName: "Vamsi Krishna D",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      userName: "jagadeesh",
      profileImg: "/avatars/boy2.png",
      fullName: "Jagadeesh P",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          userName: "jagadeesh",
          profileImg: "/avatars/girl2.png",
          fullName: "Jagadeesh P",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      userName: "srinidhi",
      profileImg: "/avatars/boy3.png",
      fullName: "Srinidhi S",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      userName: "maneesha",
      profileImg: "/avatars/boy3.png",
      fullName: "Maneesha G",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          userName: "janedoe",
          profileImg: "/avatars/girl3.png",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Vamsi Krishna D",
    userName: "vamsikrishnad",
    profileImg: "/avatars/boy2.png",
  },
  {
    _id: "2",
    fullName: "Srinidhi S",
    userName: "srinidhi",
    profileImg: "/avatars/girl1.png",
  },
  {
    _id: "3",
    fullName: "Jagadeesh P",
    userName: "jagadeesh",
    profileImg: "/avatars/boy3.png",
  },
  {
    _id: "4",
    fullName: "Maneesha G",
    userName: "maneesha",
    profileImg: "/avatars/girl2.png",
  },
];
